<?php

namespace Database\Seeders;

use App\Models\Career;
use App\Models\Discipline;
use App\Models\Semester;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DisciplineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $sistemas_de_informação = array(
            array("workload"=>36, "name" => "AEDS I", "period" => "1", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Administração", "period" => "1", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Computação e Sociedade", "period" => "1", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Fundamentos de SI", "period" => "1", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Inglês I", "period" => "1", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Introdução à Computação", "period" => "1", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Matemática Computacional", "period" => "1", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Português", "period" => "1", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "AEDS II", "period" => "2", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Arquitetura", "period" => "2", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Cálculo", "period" => "2", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "GAAL", "period" => "2", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Inglês II", "period" => "2", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Metodologia Científica", "period" => "2", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Probabilidade e Estatística", "period" => "2", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Teoria Geral dos Sistemas", "period" => "2", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Banco de Dados I", "period" => "3", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Engenharia de Software I", "period" => "3", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Cálculo Numérico", "period" => "3", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Gestão da Informação", "period" => "3", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Grafos", "period" => "3", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Programação I", "period" => "3", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "SIG", "period" => "3", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Teoria da Computação", "period" => "3", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Banco de Dados II", "period" => "4", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Engenharia de Software II", "period" => "4", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Gestão Financeira", "period" => "4", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "IHC", "period" => "4", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Marketing", "period" => "4", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Programação II", "period" => "4", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Redes", "period" => "4", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Sistemas Operacionais", "period" => "4", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Qualidade de Software", "period" => "5", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Pesquisa Operacional", "period" => "5", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Computação Gráfica", "period" => "5", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Desenvolvimento Web", "period" => "5", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Comunicação de Dados", "period" => "5", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Sistemas Distribuídos I", "period" => "5", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Inteligência Artificial", "period" => "6", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Gerência de Projeto de Software", "period" => "6", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Psicologia Organizacional", "period" => "6", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "PTCC", "period" => "6", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Optativa I", "period" => "6", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Sistemas Distribuídos II", "period" => "6", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Gestão de Processos", "period" => "7", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Empreendedorismo na Informática", "period" => "7", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Economia e Finanças", "period" => "7", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "TCC I", "period" => "7", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Optativa II", "period" => "7", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Sistemas de Apoio a Decisão", "period" => "7", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Segurança e Auditoria", "period" => "8", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Legislação e Ética", "period" => "8", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Sociologia", "period" => "8", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Filosofia e Ética", "period" => "8", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "TCC II", "period" => "8", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Optativa III", "period" => "7", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
            array("workload"=>36, "name" => "Optativa IV", "period" => "7", "semester_id" => Semester::orderBy('reference', 'desc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Sistemas de Informação')->get()->first()->id),
        );

        $enfermagem = array(
            array("workload"=>36, "name" => "Atenção Integral a Mulher", "period" => 5, "semester_id" => Semester::orderBy('reference', 'asc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Enfermagem')->get()->first()->id),
            array("workload"=>36, "name" => "Atenção Integral ao Recém-Nascido", "period" => 5, "semester_id" => Semester::orderBy('reference', 'asc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Enfermagem')->get()->first()->id),
            array("workload"=>36, "name" => "Bioética", "period" => 5, "semester_id" => Semester::orderBy('reference', 'asc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Enfermagem')->get()->first()->id),
            array("workload"=>36, "name" => "Leitura de Exames", "period" => 5, "semester_id" => Semester::orderBy('reference', 'asc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Enfermagem')->get()->first()->id),
            array("workload"=>36, "name" => "Gestão em Saúde", "period" => 5, "semester_id" => Semester::orderBy('reference', 'asc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Enfermagem')->get()->first()->id),
            array("workload"=>36, "name" => "Produção do conhecimento aplicado à Enfermagem", "period" => 5, "semester_id" => Semester::orderBy('reference', 'asc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Enfermagem')->get()->first()->id),
            array("workload"=>36, "name" => "Atividades Práticas na Atenção Primária a Saúde", "period" => 5, "semester_id" => Semester::orderBy('reference', 'asc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Enfermagem')->get()->first()->id),
            array("workload"=>36, "name" => "Atividades Práticas Serviços de Referência", "period" => 5, "semester_id" => Semester::orderBy('reference', 'asc')->get()->first()->id, "teacher_id" => User::role('teacher')->inRandomOrder()->first()->id, "career_id" => Career::where('name', 'Enfermagem')->get()->first()->id),
        );
        $cursos = [$sistemas_de_informação, $enfermagem];
        foreach ($cursos as $curso) {
            foreach ($curso as $disciplina) {
                Discipline::create($disciplina);
            }
        }
    }
}
